### ISSUE TITLE
with pdf file input - Visual parsing failed: pdf files are required

### ISSUE THREAD

**Issue by clayms** [HazyResearch/fonduer-tutorials#15]
I am running the following line, where `pdf_path` is a path to a folder that contains four pdf documents, each one of which have no issues opening in a browser, or pdf viewer.  There is nothing else in the folder.  The pdfs are not password protected.

```
corpus_parser = Parser(structural=True, lingual=True, visual=True, pdf_path=pdf_path)
%time corpus_parser.apply(doc_preprocessor, parallelism=PARALLEL)
```

I get the error below (the first error repeats twice - removed for brevity).
If I change `pdf_path` to the location of the tutorial pdf files, everything works great.
Is there some special type of pdf the `doc_preprocessor` fails on?

```
[INFO] fonduer.utils.udf - Clearing existing...
[INFO] fonduer.utils.udf - Running UDF...
[ERROR] fonduer.parser.parser - Visual parsing failed: pdf files are required
Process ParserUDF-5:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/utils/udf.py", line 169, in run
    for y in self.apply(x, **self.apply_kwargs):
  File "/home/claystevens/.venv/lib/python3.6/site-packages/fonduer/parser/parser.py", line 143, in apply
    document.name, document.sentences, self.pdf_path
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/parser/visual_linker.py", line 38, in parse_visual
    self.extract_pdf_words()
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/parser/visual_linker.py", line 54, in extract_pdf_words
    for i in range(1, int(num_pages) + 1):
ValueError: invalid literal for int() with base 10: b''
[ERROR] fonduer.parser.parser - Visual parsing failed: pdf files are required
Process ParserUDF-7:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/utils/udf.py", line 169, in run
    for y in self.apply(x, **self.apply_kwargs):
[ERROR] fonduer.parser.parser - Visual parsing failed: pdf files are required
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/parser/parser.py", line 143, in apply
    document.name, document.sentences, self.pdf_path
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/parser/visual_linker.py", line 38, in parse_visual
    self.extract_pdf_words()
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/parser/visual_linker.py", line 54, in extract_pdf_words
    for i in range(1, int(num_pages) + 1):
ValueError: invalid literal for int() with base 10: b''
Process ParserUDF-6:
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/utils/udf.py", line 169, in run
    for y in self.apply(x, **self.apply_kwargs):
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/parser/parser.py", line 143, in apply
    document.name, document.sentences, self.pdf_path
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/parser/visual_linker.py", line 38, in parse_visual
    self.extract_pdf_words()
  File "/home/user/.venv/lib/python3.6/site-packages/fonduer/parser/visual_linker.py", line 54, in extract_pdf_words
    for i in range(1, int(num_pages) + 1):
ValueError: invalid literal for int() with base 10: b''
```

**Comment by clayms** [comment]
Looks like the problem was not the pdfs, but the html files that poppler's `pdftohtml` program output.  It puts extra images in the output folder and appends the file name with a `-html`  that confuses Fonduer.  

Although in this case, the error message "Visual parsing failed: pdf files are required" is misleading.

Deleted the images, and removed the `-html` and everything works.
