### ISSUE TITLE
psycopg2.ProgrammingError: column "section_id" of relation "table" does not exist

### ISSUE THREAD

**Issue by SeekPoint** [HazyResearch/fonduer-tutorials#16]
postgres@ub1604:/home/mldl/ub16_prj/fonduer-tutorials/hardware$ python3.6 max_storage_temp_tutorial.py 
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[INFO] fonduer.meta - Connecting None to stg_temp_max:5432
[INFO] fonduer.meta - Initializing the storage schema
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)
[INFO] fonduer.utils.udf - Clearing existing...
[INFO] fonduer.utils.udf - Running UDF...
Syntax Warning: not an ICC profile, invalid signature
Syntax Warning: read ICCBased color space profile error
Syntax Warning: not an ICC profile, invalid signature
Syntax Warning: read ICCBased color space profile error
Syntax Warning: not an ICC profile, invalid signature
Syntax Warning: read ICCBased color space profile error
Syntax Warning: not an ICC profile, invalid signature
Syntax Warning: read ICCBased color space profile error
Syntax Warning: not an ICC profile, invalid signature
Syntax Warning: read ICCBased color space profile error
Syntax Warning: not an ICC profile, invalid signature
Syntax Warning: read ICCBased color space profile error
Process ParserUDF-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.ProgrammingError: column "section_id" of relation "table" does not exist
LINE 1: INSERT INTO "table" (id, document_id, position, section_id) ...
                                                        ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/fonduer/utils/udf.py", line 179, in run
    self.session.commit()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 386, in execute
    n.execute_aggregate(self, set_)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 668, in execute_aggregate
    uow)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "section_id" of relation "table" does not exist
LINE 1: INSERT INTO "table" (id, document_id, position, section_id) ...
                                                        ^
 [SQL: 'INSERT INTO "table" (id, document_id, position, section_id) VALUES (%(id)s, %(document_id)s, %(position)s, %(section_id)s)'] [parameters: ({'id': 21732, 'document_id': 21507, 'position': 0, 'section_id': 21596}, {'id': 21750, 'document_id': 21507, 'position': 1, 'section_id': 21596}, {'id': 21792, 'document_id': 21507, 'position': 2, 'section_id': 21596}, {'id': 21796, 'document_id': 21507, 'position': 3, 'section_id': 21596}, {'id': 21802, 'document_id': 21507, 'position': 4, 'section_id': 21596}, {'id': 21806, 'document_id': 21507, 'position': 5, 'section_id': 21596}, {'id': 21810, 'document_id': 21507, 'position': 6, 'section_id': 21596}, {'id': 21816, 'document_id': 21507, 'position': 7, 'section_id': 21596}  ... displaying 10 of 195 total bound parameter sets ...  {'id': 36401, 'document_id': 21559, 'position': 2, 'section_id': 21622}, {'id': 36914, 'document_id': 21559, 'position': 3, 'section_id': 21622})] (Background on this error at: http://sqlalche.me/e/f405)
Process ParserUDF-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.ProgrammingError: column "section_id" of relation "table" does not exist
LINE 1: INSERT INTO "table" (id, document_id, position, section_id) ...
                                                        ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/fonduer/utils/udf.py", line 179, in run
    self.session.commit()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 386, in execute
    n.execute_aggregate(self, set_)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 668, in execute_aggregate
    uow)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "section_id" of relation "table" does not exist
LINE 1: INSERT INTO "table" (id, document_id, position, section_id) ...
                                                        ^
 [SQL: 'INSERT INTO "table" (id, document_id, position, section_id) VALUES (%(id)s, %(document_id)s, %(position)s, %(section_id)s)'] [parameters: ({'id': 21635, 'document_id': 21508, 'position': 0, 'section_id': 21565}, {'id': 21645, 'document_id': 21508, 'position': 1, 'section_id': 21565}, {'id': 21664, 'document_id': 21508, 'position': 2, 'section_id': 21565}, {'id': 21666, 'document_id': 21508, 'position': 3, 'section_id': 21565}, {'id': 21668, 'document_id': 21508, 'position': 4, 'section_id': 21565}, {'id': 21670, 'document_id': 21508, 'position': 5, 'section_id': 21565}, {'id': 22061, 'document_id': 21508, 'position': 6, 'section_id': 21565}, {'id': 22093, 'document_id': 21508, 'position': 7, 'section_id': 21565}  ... displaying 10 of 201 total bound parameter sets ...  {'id': 37250, 'document_id': 21564, 'position': 3, 'section_id': 21595}, {'id': 37256, 'document_id': 21564, 'position': 4, 'section_id': 21595})] (Background on this error at: http://sqlalche.me/e/f405)
Process ParserUDF-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.ProgrammingError: column "section_id" of relation "table" does not exist
LINE 1: INSERT INTO "table" (id, document_id, position, section_id) ...
                                                        ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/fonduer/utils/udf.py", line 179, in run
    self.session.commit()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 386, in execute
    n.execute_aggregate(self, set_)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 668, in execute_aggregate
    uow)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "section_id" of relation "table" does not exist
LINE 1: INSERT INTO "table" (id, document_id, position, section_id) ...
                                                        ^
 [SQL: 'INSERT INTO "table" (id, document_id, position, section_id) VALUES (%(id)s, %(document_id)s, %(position)s, %(section_id)s)'] [parameters: ({'id': 26608, 'document_id': 24753, 'position': 0, 'section_id': 25993}, {'id': 26644, 'document_id': 24753, 'position': 1, 'section_id': 25993}, {'id': 26681, 'document_id': 24753, 'position': 2, 'section_id': 25993}, {'id': 26708, 'document_id': 24753, 'position': 3, 'section_id': 25993}, {'id': 26714, 'document_id': 24753, 'position': 4, 'section_id': 25993}, {'id': 26720, 'document_id': 24753, 'position': 5, 'section_id': 25993}, {'id': 26726, 'document_id': 24753, 'position': 6, 'section_id': 25993}, {'id': 27398, 'document_id': 24753, 'position': 9, 'section_id': 25993}  ... displaying 10 of 170 total bound parameter sets ...  {'id': 40802, 'document_id': 24800, 'position': 39, 'section_id': 26042}, {'id': 40810, 'document_id': 24800, 'position': 26, 'section_id': 26042})] (Background on this error at: http://sqlalche.me/e/f405)
Process ParserUDF-3:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
psycopg2.ProgrammingError: column "section_id" of relation "table" does not exist
LINE 1: INSERT INTO "table" (id, document_id, position, section_id) ...
                                                        ^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/fonduer/utils/udf.py", line 179, in run
    self.session.commit()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 386, in execute
    n.execute_aggregate(self, set_)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/unitofwork.py", line 668, in execute_aggregate
    uow)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/persistence.py", line 830, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) column "section_id" of relation "table" does not exist
LINE 1: INSERT INTO "table" (id, document_id, position, section_id) ...
                                                        ^
 [SQL: 'INSERT INTO "table" (id, document_id, position, section_id) VALUES (%(id)s, %(document_id)s, %(position)s, %(section_id)s)'] [parameters: ({'id': 30939, 'document_id': 26370, 'position': 0, 'section_id': 29021}, {'id': 30954, 'document_id': 26370, 'position': 1, 'section_id': 29021}, {'id': 30978, 'document_id': 26370, 'position': 2, 'section_id': 29021}, {'id': 31006, 'document_id': 26370, 'position': 3, 'section_id': 29021}, {'id': 31255, 'document_id': 26370, 'position': 4, 'section_id': 29021}, {'id': 31455, 'document_id': 26370, 'position': 5, 'section_id': 29021}, {'id': 31571, 'document_id': 26370, 'position': 6, 'section_id': 29021}, {'id': 31697, 'document_id': 26370, 'position': 7, 'section_id': 29021}  ... displaying 10 of 173 total bound parameter sets ...  {'id': 42920, 'document_id': 26447, 'position': 7, 'section_id': 29122}, {'id': 42937, 'document_id': 26447, 'position': 8, 'section_id': 29122})] (Background on this error at: http://sqlalche.me/e/f405)
Documents: 100
Sentences: 0
['BC337',
 'DiodesIncorporated_ZTX688BSTZ',
 'BournsInc_TIP152S',
 'DISES00645-1',
 'LITES00686-1',
 'PHGLS19500-1',
 'BC337-D',
 'DiodesIncorporated_ZTX789ASTZ',
 'CentralSemiconductorCorp_2N4013',
 'LITES00689-1',
 'MicroCommercialCo_TIP29ABP',
 'ONSMS04099-1',
 'ONSemiconductor_MMBT6521LT1',
 'BC546',
 'DiodesIncorporated_ZTX953STZ',
 'CentralSemiconductorCorp_CENU45',
 'FairchildSemiconductor_KSC2310YTA',
 'LITES00690-1',
 'LITES00424-1',
 'BC546A_Series_B14-521026',
 'DiodesIncorporated_ZXT690BKTC',
 'CentralSemiconductorCorp_CMPT5401ETR',
 'FAIRS19194-1',
 'LTSCS02910-1',
 'NXPUSAInc_PBSS5360PASX',
 'BC546-BC548C(TO-92)',
 'DIODS00215-1',
 'CentralSemiconductorCorp_CXT4033TR',
 'FAIRS25065-1',
 'LTSCS02912-1',
 'MOTOS04796-1',
 'DIODS13249-1',
 'LTSCS02920-1',
 'CSEMS02742-1',
 'Infineon-BC817KSERIES_BC818KSERIES-DS-v01_01-en',
 'MOTOS04676-1',
 '112823',
 'DISES00023-1',
 'MCCCS08610-1',
 '2N3906',
 'CSEMS03485-1',
 'Infineon-BC857SERIES_BC858SERIES_BC859SERIES_BC860SERIES-DS-v01_01-en',
 'MOTOS03189-1',
 '2N3906-D',
 'BC547',
 'DISES00189-1',
 'CSEMS05382-1',
 'INFNS19372-1',
 'MCCCS08818-1',
 '2N4123-D',
 'MicrosemiCorporation_2N2484UB',
 'DISES00192-1',
 'MCCCS08984-1',
 '2N4124',
 'CSEMS05383-1',
 'JCSTS01155-1',
 'MMMCS17742-1',
 'MOTOS03160-1',
 '2N6426-D',
 'PHGLS20267-1',
 'BC818',
 'DISES00242-1',
 'DiodesIncorporated_2DD26527',
 'KECCS03676-1',
 'MCCCS09540-1',
 '2N6427',
 'MMBT3904',
 'BC818-40LT1-D',
 'DISES00490-1',
 'AUKCS04635-1',
 'DiodesIncorporated_FCX491ATA',
 'KECCS05435-1',
 'MCCCS09741-1',
 'MINDS00015-1',
 'BC182',
 'BournsInc_BD246BS',
 'DISES00616-1',
 'DiodesIncorporated_FZT651TC',
 'MicroCommercialCo_2N3904AP',
 'BC182-D']
[INFO] fonduer.utils.udf - Clearing existing...
[INFO] fonduer.utils.udf - Running UDF...
Number of candidates: 0
[INFO] fonduer.utils.udf - Clearing existing...
[INFO] fonduer.utils.udf - Running UDF...
[========================================] 100%
Number of candidates: 0
[INFO] fonduer.utils.udf - Clearing existing...
[INFO] fonduer.utils.udf - Running UDF...
[========================================] 100%
Number of candidates: 0
Traceback (most recent call last):
  File "max_storage_temp_tutorial.py", line 340, in <module>
    F_train = featurizer.apply(split=0, replace_key_set=True, parallelism=PARALLEL)
  File "/usr/local/lib/python3.6/dist-packages/fonduer/supervision/async_annotations.py", line 297, in apply
    raise ValueError("No candidates in current split")
ValueError: No candidates in current split
postgres@ub1604:/home/mldl/ub16_prj/fonduer-tutorials/hardware$ 
postgres@ub1604:/home/mldl/ub16_prj/fonduer-tutorials/hardware$ 
postgres@ub1604:/home/mldl/ub16_prj/fonduer-tutorials/hardware$ 
postgres@ub1604:/home/mldl/ub16_prj/fonduer-tutorials/hardware$

**Comment by senwu** [comment]
Hi @loveJasmine,

It seems like your database schema is outdated. You need recreate the database and generate the schema with fonduer-v0.2.3.

Thanks,
Sen

**Comment by SeekPoint** [comment]
it works , thanks

but where is the code create the ' "table" (id, document_id, position, section_id)'
