### ISSUE TITLE
what are the all steps of postreSQL to run the example?

### ISSUE THREAD

**Issue by SeekPoint** [HazyResearch/fonduer-tutorials#8]
PostgreSQL is new to me

**Comment by senwu** [comment]
@loveJasmine 
Thanks for your question.
To run the tutorial you just need do following things:
1. install PostgreSQL which can be found in our README
2. start the server (here is an example about how you can do it: https://www.postgresql.org/docs/9.6/static/server-start.html)
3. create the database with the corresponding name (here is an example: https://www.postgresql.org/docs/9.6/static/app-createdb.html)
4. run the example

Thanks,
Sen

**Comment by SeekPoint** [comment]
I had the set the password to empty, but it still raise:

(.venv) mldl@ub1604:~/ub16_prj/__HazyResearch__/fonduer$ sudo -u postgres psql
psql (9.5.13)
Type "help" for help.

postgres=# 
postgres=# 
postgres=# sudo -i -u postgres
postgres-# createdb stg_temp_max .
postgres-# \password stg_temp_max
Enter new password: 
Enter it again: 
ERROR:  role "stg_temp_max" does not exist
postgres-#






(.venv) mldl@ub1604:~/ub16_prj/fonduer/fonduer-tutorials/hardware$ PYTHONPATH=../../ python max_storage_temp_tutorial.py 
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
[INFO] fonduer.meta - Connecting user:None to stg_temp_max:5432
[INFO] fonduer.meta - Initializing the storage schema
Traceback (most recent call last):
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1196, in _do_get
    self._dec_overflow()
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    return self._create_connection()
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 674, in __connect
    connection = pool._invoke_creator(self)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied
