### ISSUE TITLE
ValueError: Meta variables have not been initialized with a postgres connection string.

### ISSUE THREAD

**Issue by SeekPoint** [HazyResearch/fonduer-tutorials#9]
```py
PARALLEL = 4 # assuming a quad-core machine
ATTRIBUTE = "stg_temp_max"
conn_string = '//postgres:postgres:mypassword@localhost:5432/' + ATTRIBUTE
```
also:
```
(.venv) mldl@ub1604:~/ub16_prj/__HazyResearch__/fonduer$ sudo passwd -d postgres
passwd: password expiry information changed.
(.venv) mldl@ub1604:~/ub16_prj/__HazyResearch__/fonduer$ sudo -u postgres passwd
Enter new UNIX password: mypassword
Retype new UNIX password: mypassword
passwd: password updated successfully
(.venv) mldl@ub1604:~/ub16_prj/__HazyResearch__/fonduer$
```
```
(.venv) mldl@ub1604:~/ub16_prj/fonduer/fonduer-tutorials/hardware$ PYTHONPATH=../../ python max_storage_temp_tutorial.py 
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "max_storage_temp_tutorial.py", line 61, in <module>
    session = Meta.init(conn_string).Session()
  File "/home/mldl/ub16_prj/fonduer/fonduer/meta.py", line 63, in init
    Meta.Session = new_sessionmaker()
  File "/home/mldl/ub16_prj/fonduer/fonduer/meta.py", line 22, in new_sessionmaker
    "Meta variables have not been initialized with a postgres connection string."
ValueError: Meta variables have not been initialized with a postgres connection string.
(.venv) mldl@ub1604:~/ub16_prj/fonduer/fonduer-tutorials/hardware$ 
```

**Comment by lukehsiao** [comment]
Hi @loveJasmine,

You're getting this error because your connection string:
```
//postgres:postgres:mypassword@localhost:5432/
```
is not formatted correctly. It should be of the form:
```
postgres://<user>:<pw>@localhost:<port>/<database_name>
```
where `<user>`, `<pw>`, `<port>`, and `<database_name>` are replaced by their respective values. The default port for PostgreSQL is 5432. In our tutorials, we don't use a username or password at all, which is why the connection string omits those fields and just starts with `postgres://localhost:5432`. If you want do to that, you can set users to trust authentication in the pg_hba.conf file (see method 3 from [this FAQ](http://fonduer.readthedocs.io/en/latest/user/faqs.html#how-do-i-connect-to-postgresql-i-m-getting-fe-sendauth-no-password-supplied)).

You can also check out our other [FAQs](http://fonduer.readthedocs.io/en/latest/user/faqs.html) which may be helpful as you set up your PostgreSQL database.

**Comment by SeekPoint** [comment]
ATTRIBUTE = "stg_temp_max"
conn_string = 'postgres://localhost:5432/' + ATTRIBUTE

with 
```
mldl@ub1604:~/ub16_prj/fonduer/fonduer-tutorials/hardware$ service postgresql start
mldl@ub1604:~/ub16_prj/fonduer/fonduer-tutorials/hardware$ sudo -i -u postgres
[sudo] password for mldl: 
postgres@ub1604:~$ dropdb stg_temp_max
postgres@ub1604:~$ createdb stg_temp_max .
postgres@ub1604:~$ vim  /etc/postgresql/9.5/main/pg_hba.conf
```
----change all to turst

got the error:
```
(.venv) mldl@ub1604:~/ub16_prj/fonduer/fonduer-tutorials/hardware$ python max_storage_temp_tutorial.py 
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192, got 176
  return f(*args, **kwds)
[INFO] fonduer.models.meta - Connecting None to stg_temp_max:5432
[INFO] fonduer.models.meta - Initializing the storage schema
Traceback (most recent call last):
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
    return fn()
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 403, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 791, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 532, in checkout
    rec = pool._do_get()
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1196, in _do_get
    self._dec_overflow()
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 1193, in _do_get
    return self._create_connection()
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 350, in _create_connection
    return _ConnectionRecord(self)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 477, in __init__
    self.__connect(first_connect_check=True)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/pool.py", line 674, in __connect
    connection = pool._invoke_creator(self)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 106, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 412, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/mldl/ub16_prj/fonduer/.venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied
```

**Comment by lukehsiao** [comment]
It looks like you still may be missing something in setting up your PostgreSQL trust settings. I'd recommend double checking your steps from the [FAQ](http://fonduer.readthedocs.io/en/latest/user/faqs.html#how-do-i-connect-to-postgresql-i-m-getting-fe-sendauth-no-password-supplied). If you can't get that working, feel free to try one of the other methods (e.g. setting up a username and password, and providing those in the connection string).

>postgres@ub1604:~$ vim  /etc/postgresql/9.5/main/pg_hba.conf

Also note that [Fonduer does not support PostgreSQL 9.5](http://fonduer.readthedocs.io/en/latest/user/getting_started.html). You will need version 9.6+.

**Comment by SeekPoint** [comment]
I figure it out, thanks

**Comment by lukehsiao** [comment]
@loveJasmine good to hear. Would you mind posting what the issue was and how you solved it? That may help anyone in the future who happens to have a similar issue.

**Comment by SeekPoint** [comment]
summary:
```
mldl@ub1604:~/ub16_prj/fonduer/fonduer-tutorials/hardware$ sudo -i -u postgres 
postgres@ub1604:~$ 
postgres@ub1604:~$ psql
psql (9.5.13)
postgres=# createdb stg_temp_max .
postgres-# \password
Enter new password:  
Enter it again: 
postgres-# 
```

in python:
```py
PARALLEL = 4 # assuming a quad-core machine
ATTRIBUTE = "stg_temp_max"
conn_string = 'postgres://postgres:**yourpass**@localhost:5432/' + ATTRIBUTE
```
